title: Jekyll bootstrap theme
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Jekyll bootstrap theme
# Optional: this appears on the top navigation bar next to the home button

description: "Flexible Jekyll theme using bootstrap 5 as CSS framework."
# Metadata description of the website

dsw_deep_link_prefix:
# prefix for DSW deep links to a certain question

gtag: 
# Google analytics tag

plausible: 
# Plausible tag

exclude:
  - .gitignore
  - var/
  - README.md
  - vendor
  - Gemfile*
  - LICENSE

markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename:output_ext
      layout: "page"
      sidebar: main

plugins:
  - jemoji
  - jekyll-github-metadata

theme_variables: 
  theme_color: 0d6efd
  fonts:
  # List of urls towards google fonts
