title: ELIXIR toolkit theme
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

# topnav_title: ELIXIR toolkit theme
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Flexible Jekyll theme using bootstrap 5 as CSS framework."
# Metadata description of the website

dsw_deep_link_prefix:
# prefix for DSW deep links to a certain question

gtag:
# Google analytics tag

matomo:
# Matomo domain where Matomo is running

plausible: 
# Plausible tag
plausible_src: 
# default: 'https://plausible.io/js/plausible.js

exclude:
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

theme_variables: 
  # git_host: GitHub
  # back_to_top: true
  # privacy_statement_url: /privacy
  # github_buttons: 
  #   position: top
  #   edit_me: true
  #   open_issue: true
  #   history: true
  # headings:
  #   related-pages: Related pages
  #   more-information-tiles: More information
  #   resource-table-all: Tools and resources on this page
  #   affiliation-tiles-page: Affiliations
  #   contributor-minitiles-page: Contributors
  # toc:
  #   min_headings: 2
  #   headings: 'h2'
  # topnav:
    # theme: light
    # brand_logo: assets/img/main_logo.svg
    # github: true
    # twitter: false
  # theme_color: 0d6efd
  # fonts:
  #   - url towards a font

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
#   source:
#     branch: main
